export const siteConfig = {
    name: "ROUNAK NAIK",
    tagline: "Full-Stack Developer · Freelancer · Entrepreneur",
    email: "rounakpro18@gmail.com",
    location: "South Goa, India",
    college: "PCCE — B.E. Computer Engineering (2022–2027)",
    showSourceButton: false,
    social: {
        linkedin: "https://www.linkedin.com/in/rounak-naik-39354021b/",
        github: "https://github.com/Rounaknyk",
        instagram: "https://instagram.com/rounak_nyk",
    },
    stats: [
        { value: "5×", label: "Hackathon Winner" },
        { value: "9×", label: "Ideathon Winner" },
        { value: "Top 30", label: "HackIndia — 5,000+ Teams" },
        { value: "India's 1st", label: "Police Compliance App" },
    ],
    nav: [
        { key: "home", path: "/#home" },
        { key: "about", path: "/#about" },
        { key: "projects", path: "/#projects" },
        { key: "experience", path: "/#experience" },
        { key: "achievements", path: "/#achievements" },
        { key: "contact", path: "/#contact" },
    ],
    projects: [
        {
            slug: "quickpass",
            name: "QUICKPASS",
            category: "Government Tech",
            year: "2024",
            location: "Goa, India",
            role: "Lead Developer",
            badge: "🏆 Govt. Deployed · India's 1st",
            tech: ["Flutter", "Firebase", "QR Code", "Geo-tagging", "SMS API"],
            team: ["Palaash Naik", "Sayhan Ali", "Travis Fernandes"],
            image: "/quick pas.jpg",
            gallery: [
                "/quick pas.jpg",
                "/quickpass2.jpg",
                "https://images.unsplash.com/photo-1556155092-490a1ba16284?w=1200&q=80",
            ],
        },
        {
            slug: "contentai",
            name: "CONTENTAI",
            category: "AI / Marketing Automation",
            year: "2025",
            location: "Delhi (National Finals)",
            role: "Full-Stack Developer",
            badge: "🏆 Top 30 / 5,000+ · HackIndia 2025",
            tech: ["React.js", "Next.js", "Node.js", "OpenAI API", "Instagram API"],
            team: ["Sneha Karkannavar", "Pritesh Shivalingkar"],
            image: "/content ai 1.jpg",
            gallery: [
                "/content ai 1.jpg",
                "/content ai 2.jpg",
                "/content ai 3.jpg",
            ],
        },
        {
            slug: "needy-paws",
            name: "NEEDY PAWS",
            category: "Social Impact · Mobile App",
            year: "2023",
            location: "Goa, India",
            role: "Lead Developer",
            badge: "🏆 8× Ideathon Winner · Play Store",
            tech: ["Flutter", "Firebase", "Google Maps", "OpenAI", "Node.js", "MongoDB"],
            team: [],
            image: "/needy paws 1.jpg",
            gallery: [
                "/needy paws 1.jpg",
                "/needy paws 2.jpg",
                "/needy paws 3.jpg",
            ],
        },
        {
            slug: "tracq",
            name: "TRACQ",
            category: "Smart Waste Management",
            year: "2025–26",
            location: "Goa Engineering College / PCCE",
            role: "Lead Developer",
            badge: "🏆 IDEAS 4.0 Winner · Technix 2025 Winner",
            tech: ["Flutter", "Node.js", "Firebase", "AI/ML", "RFID", "CCTV Integration"],
            team: ["Rohit Binoj", "Sneha Karkannavar", "Pritesh Shivalingkar"],
            image: "/tracq 1.jpg",
            gallery: [
                "/tracq 1.jpg",
                "/tracq 2.jpg",
                "/tracq 3.jpg",
                "/IDEAS 4.0 1.jpg",
                "/IDEAS4.0 2.jpg",
                "/IDEAS4.0 3.jpg",
            ],
        },
        {
            slug: "diam-flow",
            name: "DIAM FLOW",
            category: "Web3 / Blockchain",
            year: "2024",
            location: "Hacker House Goa",
            role: "Blockchain Developer",
            badge: "🏅 4th · Top 100 / 25,000+ Teams",
            tech: ["Diamante Blockchain", "Web3", "Smart Contracts"],
            team: ["Nischal Naik", "Sanjay S. Kumar", "Shridhar Kamat"],
            image: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800&q=80",
            gallery: [
                "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=1200&q=80",
                "https://images.unsplash.com/photo-1518186285589-2f7649de83e0?w=1200&q=80",
                "https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=1200&q=80",
            ],
        },
        {
            slug: "siddharth-constructions",
            name: "SIDDHARTH CONSTRUCTIONS",
            category: "Freelance · Web Development",
            year: "2025",
            location: "Goa, India",
            role: "Full-Stack Developer",
            badge: "✅ Live on Vercel",
            tech: ["Next.js", "React.js", "Framer Motion", "EmailJS", "Vercel"],
            team: [],
            image: "/siddrath 1.jpg",
            gallery: [
                "/siddrath 1.jpg",
                "/siddrath 2.jpg",
                "/siddrath 3.jpg",
            ],
        },
    ],
    experience: [
        {
            role: "Tech Intern",
            org: "Turtlemint",
            year: "2025",
            duration: "5 months",
            desc: "Full-stack development for Motor Services vertical — Spring Boot, REST APIs, UI components",
        },
        {
            role: "ACM Student Chapter Chair",
            org: "PCCE ACM",
            year: "2024–25",
            duration: "AY 2024-25",
            desc: "Led student chapter, organized technical events and workshops",
        },
        {
            role: "Campus Ambassador",
            org: "E-Cell IIT Bombay",
            year: "2024",
            duration: "Ongoing",
            desc: "Fostering entrepreneurship at college and school levels",
        },
        {
            role: "Freelance Developer",
            org: "Global Clients",
            year: "2022–Present",
            duration: "3+ years",
            desc: "Serving clients across India, US, Netherlands, Kenya, Philippines",
        },
        {
            role: "Workshop Instructor",
            org: "GDG Goa",
            year: "2023",
            duration: "Recurring",
            desc: "Flutter app development workshop for ~100 students",
        },
        {
            role: "B.E. Computer Engineering",
            org: "PCCE (Final Year)",
            year: "2022–2027",
            duration: "5 Years",
            desc: "Padre Conceicao College of Engineering, Verna, Goa",
        },
    ],
    achievements: [
        {
            title: "IDEAS 4.0 Winner — 1st Place",
            body: "Won IDEAS 4.0 at PCCE with TraQ — Smart Waste Management System. Full circle moment from winning IDEAS 1.0 as a first-year student in 2022.",
            year: "2026",
        },
        {
            title: "Young Entrepreneur Award",
            body: "Awarded by Hon. Chief Minister of Goa, Dr. Pramod Sawant at Converge 2.0",
            year: "2025",
        },
        {
            title: "HackIndia Top 30 / AI Top 12",
            body: "National Finals, Delhi — ContentAI project out of 5,000+ teams",
            year: "2025",
        },
        {
            title: "QuickPass — Govt. Launch",
            body: "India's first police compliance pass app, officially launched by CM of Goa",
            year: "2024",
        },
        {
            title: "PCCE Special Recognition Award",
            body: "Awarded by college director for cumulative achievements in technology",
            year: "2025",
        },
        {
            title: "Technix Winner — 1st Place",
            body: "24-hour Hackathon at Goa Engineering College (Govt. of Goa)",
            year: "2025",
        },
        {
            title: "Hacker House Goa — Top 100",
            body: "4th place out of 25,000+ registrations, first-ever Web3 hackathon",
            year: "2024",
        },
    ],
    internationalClients: [
        { country: "USA", coords: { x: 20, y: 35 } },
        { country: "Netherlands", coords: { x: 48, y: 28 } },
        { country: "UAE", coords: { x: 58, y: 42 } },
        { country: "Kenya", coords: { x: 55, y: 55 } },
        { country: "Philippines", coords: { x: 78, y: 48 } },
    ],
};

export type Project = (typeof siteConfig.projects)[number];
export type Experience = (typeof siteConfig.experience)[number];
export type Achievement = (typeof siteConfig.achievements)[number];
